# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(624, 637)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 10, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 581, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.senderName = QtGui.QLineEdit(self.groupBox)
        self.senderName.setGeometry(QtCore.QRect(140, 30, 191, 31))
        self.senderName.setObjectName(_fromUtf8("senderName"))
        self.receiverName = QtGui.QLineEdit(self.groupBox)
        self.receiverName.setGeometry(QtCore.QRect(140, 70, 191, 31))
        self.receiverName.setObjectName(_fromUtf8("receiverName"))
        self.relationship = QtGui.QComboBox(self.groupBox)
        self.relationship.setGeometry(QtCore.QRect(140, 110, 191, 31))
        self.relationship.setMaxVisibleItems(4)
        self.relationship.setObjectName(_fromUtf8("relationship"))
        self.senderGender = QtGui.QComboBox(self.groupBox)
        self.senderGender.setGeometry(QtCore.QRect(340, 30, 81, 31))
        self.senderGender.setMaxVisibleItems(4)
        self.senderGender.setObjectName(_fromUtf8("senderGender"))
        self.receiverGender = QtGui.QComboBox(self.groupBox)
        self.receiverGender.setGeometry(QtCore.QRect(340, 70, 81, 31))
        self.receiverGender.setMaxVisibleItems(4)
        self.receiverGender.setObjectName(_fromUtf8("receiverGender"))
        self.dobSender = QtGui.QDateTimeEdit(self.groupBox)
        self.dobSender.setGeometry(QtCore.QRect(430, 30, 131, 31))
        self.dobSender.setObjectName(_fromUtf8("dobSender"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(470, 10, 57, 14))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.dobReciever = QtGui.QDateTimeEdit(self.groupBox)
        self.dobReciever.setGeometry(QtCore.QRect(430, 70, 131, 31))
        self.dobReciever.setObjectName(_fromUtf8("dobReciever"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(370, 10, 57, 14))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 230, 271, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.firstDate = QtGui.QDateTimeEdit(self.groupBox_2)
        self.firstDate.setGeometry(QtCore.QRect(100, 30, 131, 31))
        self.firstDate.setObjectName(_fromUtf8("firstDate"))
        self.firstKiss = QtGui.QDateTimeEdit(self.groupBox_2)
        self.firstKiss.setGeometry(QtCore.QRect(100, 70, 131, 31))
        self.firstKiss.setObjectName(_fromUtf8("firstKiss"))
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 230, 301, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.beautifulSmile = QtGui.QCheckBox(self.groupBox_3)
        self.beautifulSmile.setGeometry(QtCore.QRect(20, 30, 121, 21))
        self.beautifulSmile.setObjectName(_fromUtf8("beautifulSmile"))
        self.protective = QtGui.QCheckBox(self.groupBox_3)
        self.protective.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.protective.setObjectName(_fromUtf8("protective"))
        self.caring = QtGui.QCheckBox(self.groupBox_3)
        self.caring.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.caring.setObjectName(_fromUtf8("caring"))
        self.beautifulFriends = QtGui.QCheckBox(self.groupBox_3)
        self.beautifulFriends.setGeometry(QtCore.QRect(160, 30, 131, 21))
        self.beautifulFriends.setObjectName(_fromUtf8("beautifulFriends"))
        self.senseOfHumor = QtGui.QCheckBox(self.groupBox_3)
        self.senseOfHumor.setGeometry(QtCore.QRect(160, 60, 131, 21))
        self.senseOfHumor.setObjectName(_fromUtf8("senseOfHumor"))
        self.richDady = QtGui.QCheckBox(self.groupBox_3)
        self.richDady.setGeometry(QtCore.QRect(160, 90, 131, 21))
        self.richDady.setObjectName(_fromUtf8("richDady"))
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(19, 380, 581, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.letterTone = QtGui.QComboBox(self.groupBox_4)
        self.letterTone.setGeometry(QtCore.QRect(100, 30, 191, 31))
        self.letterTone.setMaxVisibleItems(4)
        self.letterTone.setObjectName(_fromUtf8("letterTone"))
        self.useFancyFonts = QtGui.QCheckBox(self.groupBox_4)
        self.useFancyFonts.setGeometry(QtCore.QRect(310, 30, 131, 21))
        self.useFancyFonts.setObjectName(_fromUtf8("useFancyFonts"))
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 460, 581, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.portNumber = QtGui.QLineEdit(self.groupBox_5)
        self.portNumber.setEnabled(False)
        self.portNumber.setGeometry(QtCore.QRect(140, 30, 91, 31))
        self.portNumber.setObjectName(_fromUtf8("portNumber"))
        self.startLibreOfficeButton = QtGui.QPushButton(self.groupBox_5)
        self.startLibreOfficeButton.setGeometry(QtCore.QRect(130, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.startLibreOfficeButton.setFont(font)
        self.startLibreOfficeButton.setObjectName(_fromUtf8("startLibreOfficeButton"))
        self.writeLoveLetterButton = QtGui.QPushButton(self.groupBox_5)
        self.writeLoveLetterButton.setGeometry(QtCore.QRect(300, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.writeLoveLetterButton.setFont(font)
        self.writeLoveLetterButton.setObjectName(_fromUtf8("writeLoveLetterButton"))
        self.fileName = QtGui.QLineEdit(self.groupBox_5)
        self.fileName.setGeometry(QtCore.QRect(370, 30, 191, 31))
        self.fileName.setObjectName(_fromUtf8("fileName"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(280, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(370, 610, 251, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Py LibreOffice Love Letter Writer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Py LibreOffice Love Letter Writer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Sender and Reciever", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Sender\'s Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Receiver\'s Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Relationship:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "DOB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Sex", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Important Dates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "First Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "First Kiss:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Reasons You Fell In Love", None, QtGui.QApplication.UnicodeUTF8))
        self.beautifulSmile.setText(QtGui.QApplication.translate("Form", "Beautiful Smile", None, QtGui.QApplication.UnicodeUTF8))
        self.protective.setText(QtGui.QApplication.translate("Form", "Protective", None, QtGui.QApplication.UnicodeUTF8))
        self.caring.setText(QtGui.QApplication.translate("Form", "Caring", None, QtGui.QApplication.UnicodeUTF8))
        self.beautifulFriends.setText(QtGui.QApplication.translate("Form", "Beautiful Friends", None, QtGui.QApplication.UnicodeUTF8))
        self.senseOfHumor.setText(QtGui.QApplication.translate("Form", "Sense of Humor", None, QtGui.QApplication.UnicodeUTF8))
        self.richDady.setText(QtGui.QApplication.translate("Form", "Rich Daddy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Miscellaneous Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Letter Tone:", None, QtGui.QApplication.UnicodeUTF8))
        self.useFancyFonts.setText(QtGui.QApplication.translate("Form", "Use Fancy Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "LibreOffice", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Port Number", None, QtGui.QApplication.UnicodeUTF8))
        self.startLibreOfficeButton.setText(QtGui.QApplication.translate("Form", "Start LibreOffice", None, QtGui.QApplication.UnicodeUTF8))
        self.writeLoveLetterButton.setText(QtGui.QApplication.translate("Form", "Write Love Letter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Developed by Kunal Deo for LUD Tutorial", None, QtGui.QApplication.UnicodeUTF8))

